spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: cloud_config_dev
server:
  port: 8899
---
spring:
  profiles: test
  application:
    name: cloud_config_test
server:
  port: 8855